# Generated by Django 5.1.7 on 2025-04-18 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_utilisateur_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
