# Generated by Django 5.1.7 on 2025-05-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='titre',
            field=models.CharField(default='Problème de commande', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('ASSIGNÉ', 'Assigné'), ('EN COURS', 'En cours'), ('RÉSOLU', 'Résolu'), ('REJETÉ', 'Rejeté')], default='CREÉ', max_length=20),
        ),
    ]
