# Generated by Django 5.1.7 on 2025-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_ticket_titre_alter_ticket_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('ASSIGNÉ', 'Assigné'), ('EN COURS', 'En cours'), ('RÉSOLU', 'Résolu'), ('REJETÉ', 'Rejeté')], default='Assigné', max_length=20),
        ),
    ]
